version: '3.7'

services:
gapp-redis:
    image: bitnami/redis:6.2
    container_name: gapp-redis
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --loglevel warning --protected-mode no
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - gapp-redis-data:/data 
gapp-database:
    image: mysql:8.0
    ports:
      - "3308:3306"
    container_name: gapp-database
    volumes:
      - dbdata:/var/lib/mysql
    restart: always
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment: 
      MYSQL_ROOT_PASSWORD: gameappRoo7t0lk2o20
      MYSQL_DATABASE: gameapp_db
      MYSQL_USER: gameapp
      MYSQL_PASSWORD: gameappt0lk2o20


volumes:
  dbdata:dbdata:
  gameapp-redis-data: